# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pose.v1 import session_pb2 as pose_dot_v1_dot_session__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pose/v1/session_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PoseSessionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Discover = channel.unary_unary(
                '/pose.v1.PoseSessionService/Discover',
                request_serializer=pose_dot_v1_dot_session__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=pose_dot_v1_dot_session__pb2.DiscoverResponse.FromString,
                _registered_method=True)
        self.PlanSession = channel.unary_unary(
                '/pose.v1.PoseSessionService/PlanSession',
                request_serializer=pose_dot_v1_dot_session__pb2.PlanSessionRequest.SerializeToString,
                response_deserializer=pose_dot_v1_dot_session__pb2.PlanSessionResponse.FromString,
                _registered_method=True)
        self.LeaseRegions = channel.unary_unary(
                '/pose.v1.PoseSessionService/LeaseRegions',
                request_serializer=pose_dot_v1_dot_session__pb2.LeaseRegionsRequest.SerializeToString,
                response_deserializer=pose_dot_v1_dot_session__pb2.LeaseRegionsResponse.FromString,
                _registered_method=True)
        self.GenerateInnerPoRep = channel.unary_unary(
                '/pose.v1.PoseSessionService/GenerateInnerPoRep',
                request_serializer=pose_dot_v1_dot_session__pb2.GenerateInnerPoRepRequest.SerializeToString,
                response_deserializer=pose_dot_v1_dot_session__pb2.GenerateInnerPoRepResponse.FromString,
                _registered_method=True)
        self.MaterializeRegionPayloads = channel.unary_unary(
                '/pose.v1.PoseSessionService/MaterializeRegionPayloads',
                request_serializer=pose_dot_v1_dot_session__pb2.MaterializeRegionPayloadsRequest.SerializeToString,
                response_deserializer=pose_dot_v1_dot_session__pb2.MaterializeRegionPayloadsResponse.FromString,
                _registered_method=True)
        self.CommitRegions = channel.unary_unary(
                '/pose.v1.PoseSessionService/CommitRegions',
                request_serializer=pose_dot_v1_dot_session__pb2.CommitRegionsRequest.SerializeToString,
                response_deserializer=pose_dot_v1_dot_session__pb2.CommitRegionsResponse.FromString,
                _registered_method=True)
        self.VerifyInnerProofs = channel.unary_unary(
                '/pose.v1.PoseSessionService/VerifyInnerProofs',
                request_serializer=pose_dot_v1_dot_session__pb2.VerifyInnerProofsRequest.SerializeToString,
                response_deserializer=pose_dot_v1_dot_session__pb2.VerifyInnerProofsResponse.FromString,
                _registered_method=True)
        self.ChallengeOuter = channel.unary_unary(
                '/pose.v1.PoseSessionService/ChallengeOuter',
                request_serializer=pose_dot_v1_dot_session__pb2.ChallengeOuterRequest.SerializeToString,
                response_deserializer=pose_dot_v1_dot_session__pb2.ChallengeOuterResponse.FromString,
                _registered_method=True)
        self.VerifyOuter = channel.unary_unary(
                '/pose.v1.PoseSessionService/VerifyOuter',
                request_serializer=pose_dot_v1_dot_session__pb2.VerifyOuterRequest.SerializeToString,
                response_deserializer=pose_dot_v1_dot_session__pb2.VerifyOuterResponse.FromString,
                _registered_method=True)
        self.Finalize = channel.unary_unary(
                '/pose.v1.PoseSessionService/Finalize',
                request_serializer=pose_dot_v1_dot_session__pb2.FinalizeRequest.SerializeToString,
                response_deserializer=pose_dot_v1_dot_session__pb2.FinalizeResponse.FromString,
                _registered_method=True)
        self.Cleanup = channel.unary_unary(
                '/pose.v1.PoseSessionService/Cleanup',
                request_serializer=pose_dot_v1_dot_session__pb2.CleanupRequest.SerializeToString,
                response_deserializer=pose_dot_v1_dot_session__pb2.CleanupResponse.FromString,
                _registered_method=True)


class PoseSessionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Discover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaseRegions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateInnerPoRep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MaterializeRegionPayloads(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitRegions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyInnerProofs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChallengeOuter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyOuter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Finalize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cleanup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PoseSessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=pose_dot_v1_dot_session__pb2.DiscoverRequest.FromString,
                    response_serializer=pose_dot_v1_dot_session__pb2.DiscoverResponse.SerializeToString,
            ),
            'PlanSession': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanSession,
                    request_deserializer=pose_dot_v1_dot_session__pb2.PlanSessionRequest.FromString,
                    response_serializer=pose_dot_v1_dot_session__pb2.PlanSessionResponse.SerializeToString,
            ),
            'LeaseRegions': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaseRegions,
                    request_deserializer=pose_dot_v1_dot_session__pb2.LeaseRegionsRequest.FromString,
                    response_serializer=pose_dot_v1_dot_session__pb2.LeaseRegionsResponse.SerializeToString,
            ),
            'GenerateInnerPoRep': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateInnerPoRep,
                    request_deserializer=pose_dot_v1_dot_session__pb2.GenerateInnerPoRepRequest.FromString,
                    response_serializer=pose_dot_v1_dot_session__pb2.GenerateInnerPoRepResponse.SerializeToString,
            ),
            'MaterializeRegionPayloads': grpc.unary_unary_rpc_method_handler(
                    servicer.MaterializeRegionPayloads,
                    request_deserializer=pose_dot_v1_dot_session__pb2.MaterializeRegionPayloadsRequest.FromString,
                    response_serializer=pose_dot_v1_dot_session__pb2.MaterializeRegionPayloadsResponse.SerializeToString,
            ),
            'CommitRegions': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitRegions,
                    request_deserializer=pose_dot_v1_dot_session__pb2.CommitRegionsRequest.FromString,
                    response_serializer=pose_dot_v1_dot_session__pb2.CommitRegionsResponse.SerializeToString,
            ),
            'VerifyInnerProofs': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyInnerProofs,
                    request_deserializer=pose_dot_v1_dot_session__pb2.VerifyInnerProofsRequest.FromString,
                    response_serializer=pose_dot_v1_dot_session__pb2.VerifyInnerProofsResponse.SerializeToString,
            ),
            'ChallengeOuter': grpc.unary_unary_rpc_method_handler(
                    servicer.ChallengeOuter,
                    request_deserializer=pose_dot_v1_dot_session__pb2.ChallengeOuterRequest.FromString,
                    response_serializer=pose_dot_v1_dot_session__pb2.ChallengeOuterResponse.SerializeToString,
            ),
            'VerifyOuter': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOuter,
                    request_deserializer=pose_dot_v1_dot_session__pb2.VerifyOuterRequest.FromString,
                    response_serializer=pose_dot_v1_dot_session__pb2.VerifyOuterResponse.SerializeToString,
            ),
            'Finalize': grpc.unary_unary_rpc_method_handler(
                    servicer.Finalize,
                    request_deserializer=pose_dot_v1_dot_session__pb2.FinalizeRequest.FromString,
                    response_serializer=pose_dot_v1_dot_session__pb2.FinalizeResponse.SerializeToString,
            ),
            'Cleanup': grpc.unary_unary_rpc_method_handler(
                    servicer.Cleanup,
                    request_deserializer=pose_dot_v1_dot_session__pb2.CleanupRequest.FromString,
                    response_serializer=pose_dot_v1_dot_session__pb2.CleanupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pose.v1.PoseSessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pose.v1.PoseSessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PoseSessionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pose.v1.PoseSessionService/Discover',
            pose_dot_v1_dot_session__pb2.DiscoverRequest.SerializeToString,
            pose_dot_v1_dot_session__pb2.DiscoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pose.v1.PoseSessionService/PlanSession',
            pose_dot_v1_dot_session__pb2.PlanSessionRequest.SerializeToString,
            pose_dot_v1_dot_session__pb2.PlanSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaseRegions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pose.v1.PoseSessionService/LeaseRegions',
            pose_dot_v1_dot_session__pb2.LeaseRegionsRequest.SerializeToString,
            pose_dot_v1_dot_session__pb2.LeaseRegionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateInnerPoRep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pose.v1.PoseSessionService/GenerateInnerPoRep',
            pose_dot_v1_dot_session__pb2.GenerateInnerPoRepRequest.SerializeToString,
            pose_dot_v1_dot_session__pb2.GenerateInnerPoRepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MaterializeRegionPayloads(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pose.v1.PoseSessionService/MaterializeRegionPayloads',
            pose_dot_v1_dot_session__pb2.MaterializeRegionPayloadsRequest.SerializeToString,
            pose_dot_v1_dot_session__pb2.MaterializeRegionPayloadsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitRegions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pose.v1.PoseSessionService/CommitRegions',
            pose_dot_v1_dot_session__pb2.CommitRegionsRequest.SerializeToString,
            pose_dot_v1_dot_session__pb2.CommitRegionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyInnerProofs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pose.v1.PoseSessionService/VerifyInnerProofs',
            pose_dot_v1_dot_session__pb2.VerifyInnerProofsRequest.SerializeToString,
            pose_dot_v1_dot_session__pb2.VerifyInnerProofsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChallengeOuter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pose.v1.PoseSessionService/ChallengeOuter',
            pose_dot_v1_dot_session__pb2.ChallengeOuterRequest.SerializeToString,
            pose_dot_v1_dot_session__pb2.ChallengeOuterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyOuter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pose.v1.PoseSessionService/VerifyOuter',
            pose_dot_v1_dot_session__pb2.VerifyOuterRequest.SerializeToString,
            pose_dot_v1_dot_session__pb2.VerifyOuterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Finalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pose.v1.PoseSessionService/Finalize',
            pose_dot_v1_dot_session__pb2.FinalizeRequest.SerializeToString,
            pose_dot_v1_dot_session__pb2.FinalizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cleanup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pose.v1.PoseSessionService/Cleanup',
            pose_dot_v1_dot_session__pb2.CleanupRequest.SerializeToString,
            pose_dot_v1_dot_session__pb2.CleanupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
